Website = "https://github.com/bytemystery-com/vboxssh"

[Details]
Icon = "assets/icons/icon.png"
Name = "VBoxSsh"
ID = "com.bytemystery.vboxssh"
Version = "0.2.5"
Build = 96

[LinuxAndBSD]
GenericName = "Virtualbox Frontend"
Categories = ["System"]
Comment = "Manage VirtualBox locally and over SSH"
Keywords = ["virtualbox", "ssh", "frontend"]
